sudo: false

language: c

addons:
  apt:
    packages:
    - libgmp-dev

cache:
  directories:
    - $HOME/.stack/

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack update
  - stack setup
  - stack install hlint
  - stack build skylark-core --only-dependencies

script:
  - ./lint.sh
  - printenv
  # Unit tests require AWS keys in the environment, but somehow aren't
  # picking them up in the env declaration abovel.
  - AWS_SECRET_ACCESS_KEY=foo AWS_ACCESS_KEY_ID=bar stack build skylark-core --test --bench
